#!/usr/bin/env bash
# shellcheck disable=SC2016
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd -P)"
while IFS= read -r target; do
    grep -Eq "^${target}:" "$root/Makefile" || {
        echo 'error: release checklist names a missing make target' >&2
        exit 1
    }
done < <(grep -oE 'make [a-z][a-z0-9-]+' "$root/RELEASE_CHECKLIST.md" | awk '{print $2}' | sort -u)
scratch="$(cd "$(mktemp -d)" && pwd -P)"
trap 'rm -rf "$scratch"' EXIT
mkdir -p "$scratch/v1.2.3"
printf 'Release v1.2.3\n' >"$scratch/v1.2.3/message.txt"
export WAITPRIMS_RELEASE_TAG=v1.2.3
export WAITPRIMS_TAG_MESSAGE_DIR="$scratch/v1.2.3"
export WAITPRIMS_TAGGER_NAME='3 Leaps Infosec Team'
export WAITPRIMS_TAGGER_EMAIL='infosec@3leaps.net'
source "$root/scripts/release-tag-common.sh"
mkdir -p "$scratch/trusted/config/release" "$scratch/trusted/scripts"
printf '%s\n' '3 Leaps Infosec Team <infosec@3leaps.net>' >"$scratch/trusted/config/release/tagger-identity.txt"
cp "$root/scripts/"{release-prepare-tag-message.py,release-tag-body.sh} "$scratch/trusted/scripts/"
tag_root="$scratch/trusted"
expect_fail() { if "$@" >/dev/null 2>&1; then
    echo "expected rejection: $*" >&2
    exit 1
fi; }
tag_identity
[[ "$(tag_message_file)" == "$scratch/v1.2.3/message.txt" ]]
ln -s "$scratch" "$scratch/symlink-parent"
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR="$scratch/symlink-parent/v1.2.3" bash -c 'source "$1"; tag_message_file' _ "$root/scripts/release-tag-common.sh"
printf 'Release v1.2.3' >"$scratch/v1.2.3/message.txt"
expect_fail tag_message_file
printf 'Release v1.2.3  \n' >"$scratch/v1.2.3/message.txt"
expect_fail tag_message_file
printf 'Generated by <model>\n' >"$scratch/v1.2.3/message.txt"
expect_fail tag_message_file
printf 'Generated by <REPLACE-model>\n' >"$scratch/v1.2.3/message.txt"
expect_fail tag_message_file
printf 'Release v1.2.3\n' >"$scratch/v1.2.3/message.txt"
expect_fail env WAITPRIMS_TAGGER_NAME=$'bad\nname' bash -c 'source "$1"; tag_identity' _ "$root/scripts/release-tag-common.sh"
expect_fail env WAITPRIMS_TAGGER_EMAIL='a<b>' bash -c 'source "$1"; tag_identity' _ "$root/scripts/release-tag-common.sh"
expect_fail env -u WAITPRIMS_TAG_MESSAGE_DIR bash -c 'source "$1"; tag_message_file' _ "$root/scripts/release-tag-common.sh"
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR="$scratch" bash -c 'source "$1"; tag_message_file' _ "$root/scripts/release-tag-common.sh"
export WAITPRIMS_PGP_KEY_ID=0123456789ABCDEF
expect_fail tag_selector_shape
unset WAITPRIMS_PGP_KEY_ID
expect_fail tag_selector_shape
git init -q -b main "$scratch/repo"
git -C "$scratch/repo" config user.name fixture
git -C "$scratch/repo" config user.email fixture@example.invalid
printf 'x\n' >"$scratch/repo/file"
git -C "$scratch/repo" add file
git -C "$scratch/repo" commit -qm fixture
git -C "$scratch/repo" tag v1.2.3
export WAITPRIMS_PGP_KEY_ID=0123456789ABCDEF0123456789ABCDEF01234567!
(
    cd "$scratch/repo"
    expect_fail tag_verify_object refs/tags/v1.2.3 'Release v1.2.3'
)
mkdir -p "$scratch/bin"
cat >"$scratch/bin/gh" <<'SH'
#!/usr/bin/env bash
[[ "${GH_TEST_FAIL:-0}" == 0 ]] || exit 1
if [[ "$*" == *'rulesets?includes_parents=true&per_page=100'* ]]; then
	cat "$RULESET_LIST"
else
	cat "$RULESET_FIXTURE"
fi
SH
chmod +x "$scratch/bin/gh"
export PATH="$scratch/bin:$PATH" RULESET_FIXTURE="$scratch/ruleset.json" RULESET_LIST="$scratch/list.json"
printf '[[{"id":7,"name":"Unrelated display name","target":"tag","enforcement":"active"}]]\n' >"$RULESET_LIST"
cat >"$RULESET_FIXTURE" <<'JSON'
{"name":"Unrelated display name","source_type":"Organization","source":"3leaps","target":"tag","enforcement":"active","conditions":{"ref_name":{"exclude":[],"include":["refs/tags/v*"]}},"rules":[{"type":"creation"},{"type":"deletion"},{"type":"non_fast_forward"},{"type":"update"}],"bypass_actors":[{"actor_id":null,"actor_type":"OrganizationAdmin","bypass_mode":"always"}]}
JSON
report="$root/scripts/release-inspect-tag-ruleset.sh"
[[ "$("$report" v1.2.3)" == FOUND:* ]]
jq 'del(.bypass_actors)' "$scratch/ruleset.json" >"$scratch/hidden.json"
export RULESET_FIXTURE="$scratch/hidden.json"
[[ "$("$report" v1.2.3)" == UNKNOWN:* ]]
export RULESET_FIXTURE="$scratch/ruleset.json"
jq '.conditions.ref_name.exclude = ["refs/tags/v1.2.3"]' "$RULESET_FIXTURE" >"$scratch/excluded.json"
export RULESET_FIXTURE="$scratch/excluded.json"
[[ "$("$report" v1.2.3)" == ABSENT:* ]]
jq '.conditions.ref_name.exclude = ["~UNSUPPORTED"]' "$scratch/ruleset.json" >"$scratch/unknown.json"
export RULESET_FIXTURE="$scratch/unknown.json"
[[ "$("$report" v1.2.3)" == UNKNOWN:* ]]
jq '.rules = [] | .name = "Tag Publish Protection"' "$scratch/ruleset.json" >"$scratch/empty.json"
export RULESET_FIXTURE="$scratch/empty.json"
[[ "$("$report" v1.2.3)" == ABSENT:* ]]
jq '.enforcement = "disabled" | .name = "Tag Publish Protection"' "$scratch/ruleset.json" >"$scratch/inactive.json"
export RULESET_FIXTURE="$scratch/inactive.json"
[[ "$("$report" v1.2.3)" == ABSENT:* ]]
export RULESET_FIXTURE="$scratch/ruleset.json"
[[ "$(GH_TEST_FAIL=1 "$report" v1.2.3)" == UNKNOWN:* ]]
jq '.bypass_actors = [{"actor_type":"Team","bypass_mode":"always","actor_id":2}]' "$RULESET_FIXTURE" >"$scratch/team-bypass.json"
export RULESET_FIXTURE="$scratch/team-bypass.json"
[[ "$("$report" v1.2.3)" == *'bypass=Team:always'* ]]
jq 'del(.target)' "$scratch/ruleset.json" >"$scratch/incomplete.json"
export RULESET_FIXTURE="$scratch/incomplete.json"
[[ "$("$report" v1.2.3)" == UNKNOWN:* ]]
export RULESET_FIXTURE="$scratch/ruleset.json"
printf '[]\n' >"$RULESET_LIST"
[[ "$("$report" v1.2.3)" == ABSENT:* ]]
printf 'bad json\n' >"$RULESET_LIST"
[[ "$("$report" v1.2.3)" == UNKNOWN:* ]]
printf '[[{"id":7,"target":"tag","enforcement":"active"}]]\n' >"$RULESET_LIST"
export RULESET_FIXTURE="$scratch/ruleset.json"
git -C "$scratch/repo" tag -d v1.2.3 >/dev/null
git -C "$scratch/repo" update-ref refs/remotes/origin/main "$(git -C "$scratch/repo" rev-parse HEAD)"
tag_expected_message >"$scratch/expected-message"
cmp -s "$scratch/expected-message" "$scratch/v1.2.3/message.txt"
printf 'Changed message\n' >"$scratch/wrong-message"
(
    cd "$scratch/repo"
    GIT_COMMITTER_NAME="$WAITPRIMS_TAGGER_NAME" GIT_COMMITTER_EMAIL="$WAITPRIMS_TAGGER_EMAIL" \
        git tag -a --cleanup=verbatim v1.2.3 -F "$scratch/expected-message"
)
(
    cd "$scratch/repo"
    tag_verify_object refs/tags/v1.2.3 "$scratch/expected-message"
)
(
    cd "$scratch/repo"
    expect_fail tag_verify_object refs/tags/v1.2.3 "$scratch/wrong-message"
)
printf 'Release v1.2.3\n\n' >"$scratch/extra-blank-lines"
(
    cd "$scratch/repo"
    GIT_COMMITTER_NAME="$WAITPRIMS_TAGGER_NAME" GIT_COMMITTER_EMAIL="$WAITPRIMS_TAGGER_EMAIL" \
        git tag -fa --cleanup=verbatim v1.2.3 -F "$scratch/extra-blank-lines" >/dev/null
    expect_fail tag_verify_object refs/tags/v1.2.3 "$scratch/expected-message"
)
echo '[ok] signed-tag negative controls passed'
