#!/usr/bin/env bash
# No live key, GitHub operation, or tag: exercise only an isolated message fixture.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd -P)"
scratch="$(cd "$(mktemp -d)" && pwd -P)"
trap 'rm -rf "$scratch"' EXIT
mkdir -p "$scratch/repo/scripts" "$scratch/external" "$scratch/bin"
cp "$root/scripts/release-tag-operator.sh" "$root/scripts/release-prepare-tag-message.py" "$scratch/repo/scripts/"
printf '1.2.3\n' >"$scratch/repo/VERSION"
cat >"$scratch/bin/git" <<'SH'
#!/usr/bin/env bash
printf 'git operation attempted\n' >>"$TRACE"
exit 1
SH
chmod +x "$scratch/bin/git" "$scratch/repo/scripts/"*
export PATH="$scratch/bin:$PATH" TRACE="$scratch/trace" WAITPRIMS_RELEASE_TAG=v1.2.3
operator="$scratch/repo/scripts/release-tag-operator.sh"
directory="$scratch/external/v1.2.3"
export WAITPRIMS_TAG_MESSAGE_DIR="$directory"
expect_fail() {
    if "$@" >"$scratch/output" 2>&1; then
        echo 'error: expected message-preparation rejection' >&2
        exit 1
    fi
}
expect_fail env -u WAITPRIMS_RELEASE_TAG "$operator" prepare-message
expect_fail env WAITPRIMS_RELEASE_TAG=v1.2.4 "$operator" prepare-message
expect_fail env -u WAITPRIMS_TAG_MESSAGE_DIR "$operator" prepare-message
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR=relative/v1.2.3 "$operator" prepare-message
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR="$scratch/repo/v1.2.3" "$operator" prepare-message
[[ ! -e "$scratch/repo/v1.2.3" ]]
mkdir -p "$scratch/external/alternate"
mkdir -p "$scratch/external/shortcut"
ln -s "$scratch/external/alternate" "$scratch/external/shortcut/v1.2.3"
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR="$scratch/external/shortcut/v1.2.3" "$operator" prepare-message
ln -s "$scratch/repo" "$scratch/external/inside-repo"
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR="$scratch/external/inside-repo/v1.2.3" "$operator" prepare-message
ln -s "$scratch/external/alternate" "$scratch/external/outside-link"
expect_fail env WAITPRIMS_TAG_MESSAGE_DIR="$scratch/external/outside-link/v1.2.3" "$operator" prepare-message
[[ ! -e "$TRACE" ]]

"$operator" prepare-message >"$scratch/output"
[[ "$(cat "$directory/message.txt")" == 'waitprims v1.2.3' ]]
[[ "$(wc -c <"$directory/message.txt" | tr -d '[:space:]')" == 17 ]]
grep -q '^\[ok\] created public tag message' "$scratch/output"
"$operator" prepare-message >"$scratch/output"
grep -q '^\[ok\] preserved public tag message' "$scratch/output"
printf 'Custom approved title\n' >"$directory/message.txt"
"$operator" prepare-message >"$scratch/output"
[[ "$(cat "$directory/message.txt")" == 'Custom approved title' ]]
printf 'Generated by <model>\n' >"$directory/message.txt"
expect_fail "$operator" prepare-message
printf 'Release <TODO-version>\n' >"$directory/message.txt"
expect_fail "$operator" prepare-message
printf 'Published by <release@example.invalid>\n' >"$directory/message.txt"
"$operator" prepare-message >"$scratch/output"
printf 'Bad trailing space \n' >"$directory/message.txt"
expect_fail "$operator" prepare-message
rm "$directory/message.txt"
ln -s "$scratch/external/alternate" "$directory/message.txt"
expect_fail "$operator" prepare-message
rm "$directory/message.txt"
printf 'Custom approved title\n' >"$directory/message.txt"

# Optional external loader works even with no signing variables; sourcing it
# changes directory, which the operator must restore before preparing text.
cat >"$scratch/external/loader" <<'SH'
cd "$FIXTURE_AWAY"
export WAITPRIMS_TAG_MESSAGE_DIR="$FIXTURE_MESSAGE_DIR"
SH
export FIXTURE_AWAY="$scratch/external" FIXTURE_MESSAGE_DIR="$directory"
env -u WAITPRIMS_TAG_MESSAGE_DIR WAITPRIMS_APPROVED_ENV_LOADER="$scratch/external/loader" \
    "$operator" prepare-message >"$scratch/output"
grep -q 'Custom approved title' "$scratch/output"
[[ ! -e "$TRACE" ]]
echo '[ok] external message creation, review, no-clobber and unsafe-path controls passed'
